### PR TITLE
Fix locale and string encoding

### PR DESCRIPTION
**Pull request by TonyCTHsu**
**Why** 

Discovered that the string encoding is `US-ASCII`

```bash
root@0f792b26260a:/# irb
irb(main):001:0> "".encoding
=> #<Encoding:US-ASCII>
```
Locale was not set correctly:

```bash
root@0f792b26260a:/# locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.utf8
POSIX
root@0f792b26260a:/# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**How**

Before in the build process:

```
RUN locale-gen en_US.UTF-8
Generating locales (this might take a while)...
Generation complete.
```

How success looks like after the change 

```
RUN locale-gen en_US.UTF-8
Generating locales (this might take a while)...
   en_US.UTF-8... done
Generation complete.
```

> [!NOTE]
> `locale-gen` generate localisation files from templates (`/etc/locales.gen`).

### CODE REVIEW

**Review by anmarchenko — APPROVED** [review]

**Comment by p-datadog** [comment]
Would it be helpful to add a check that the needed locale actually got generated, i.e. `locale -a|grep UTF-8`, and that it's used by Ruby, e.g.

```
 test  "`ruby -e 'puts "".encoding'`" = UTF-8
```

?

**Comment by lloeki** [comment]
@p-datadog I was thinking about that as well, if only to be able to check that this PR works as expected across the board by having it checking itself instead of going through this PR's generated images manually.

**Comment by lloeki** [comment]
I've added a couple test cases and a test harness, failure on some older rubies is expected at this stage because of the `minitest` version. I'll improve a bit upon it.

**Review by p-datadog — APPROVED** [review]
Awesome!

**Review by marcotc — APPROVED** [review]

**Review by lloeki — APPROVED** [review]

**Comment by lloeki** [comment]
Pushing images with https://github.com/DataDog/images-rb/actions/runs/9783505263

**Pull request merged**
